## TLDR:
- Tensors can be converted to and from other data types
- Tensors have attributes
- Tensors can be tranferred between the CPU and GPU
- Tensors can be used as arrays
- Tensors can be used as matrices
- Tensors can operate on shared memory with other objects

## Tensor Conversions

In [13]:
import torch
import numpy as np

# Tensor from Python array
py_array = [[1, 2], [3, 4]]
from_py = torch.tensor(py_array) # Tensor from `py_array`
print(f"from_py =\n{from_py}")
print()

# Tensor from numpy array
np_array = np.array(py_array)
from_np = torch.tensor(np_array) # Tensor from `np_array`
print(f"from_np =\n{from_np}")
print()

# Tensor similar to an existing tensor
# - Retains properties of argument tensor
#   unless explicitly overriden (shape,
#   data type, etc.)
ones_like = torch.ones_like(from_py)                    # Tensor of ones similar to `from_py`
rand_like = torch.rand_like(from_py, dtype=torch.float) # Tensor of random values similar to `from_py`
print(f"ones_like =\n{ones_like}")
print(f"rand_like =\n{rand_like}")
print()

# Tensor from shape
# - Values dependent on the function
# - Shape dependent on the argument
shape = (2, 4)
ones = torch.ones(shape)   # Tensor of ones of shape (2, 4)
rand = torch.rand(shape)   # Tensor of random values of shape (2, 4)
zeros = torch.zeros(shape) # Tensor of zeros of shape (2, 4)
print(f"ones =\n{ones}")
print(f"rand =\n{rand}")
print(f"zeros =\n{zeros}")
print()

from_py =
tensor([[1, 2],
        [3, 4]])

from_np =
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

ones_like =
tensor([[1, 1],
        [1, 1]])
rand_like =
tensor([[0.6822, 0.4029],
        [0.6310, 0.7154]])

ones =
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
rand =
tensor([[0.9327, 0.7215, 0.9513, 1.0000],
        [0.1872, 0.3786, 0.1766, 0.9017]])
zeros =
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])



Tensors can be initialized in various ways including:
- From Python array
- From numpy array
- From existing tensor
- From shape

## Tensor Attributes

In [14]:
tensor = torch.rand(3, 4)

print(f"tensor.shape = {tensor.shape}")   # Shape (dimensions) of `tensor`
print(f"tensor.dtype = {tensor.dtype}")   # Data type of `tensor`
print(f"tensor.device = {tensor.device}") # Device `tensor` is stored on

tensor.shape = torch.Size([3, 4])
tensor.dtype = torch.float32
tensor.device = cpu


Tensors have attributes, such as:
- Shape
- Data type
- Device (on which it is stored on)

## Tensors on the GPU

In [15]:
# We can move the tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to("cuda") # Move tensor to CUDA GPU
print(f"tensor.device = {tensor.device}") # Device `tensor` is stored on

tensor.device = cpu


Tensors can be moved to and from the GPU

## Tensors as Arrays

In [16]:
# Numpy-based indexing and slicing
# - Indexing can be thought of as follows: all elements 
#   that satisfy the provided indexing are returned, e.g.:
#   - "..." and ":" mean the indices in that dimension
#     can be anything
#   - `0` means the indices in that dimension must equal
#     `0`
#   - `::2` means the indices in that dimension must be
#     included in the set of visited indices when
#     iterating through all indices of that dimension
#     with stride `2`
tensor = torch.ones(3, 4)
print(f"tensor[0] =\n{tensor[0]}")             # First row
print(f"tensor[:, 0] =\n{tensor[:, 0]}")       # First column
print(f"tensor[..., -1] =\n{tensor[..., -1]}") # Last column
print()

modified = tensor
modified[..., ::2] = 0 # Assign to `0` every element such that
                       # the row is anything and the column
                       # is even
print(f"modified =\n{modified}")
print()

# Joining (concatenating) tensors
# - Joining can be thought of as follows: provided a
#   dimension, we can think of the tensor as 1D array,
#   where each element of this array corresponds to
#   each index along the dimension in the tensor.
#   Now, the two 1D arrays can be concatenated normally.
joined_0 = torch.cat([modified, modified], dim=0) # Joining rows
joined_1 = torch.cat([modified, modified], dim=1) # Joining columns
print(f"joined_0 =\n{joined_0}")
print(f"joined_1 =\n{joined_1}")
print()

tensor[0] =
tensor([1., 1., 1., 1.])
tensor[:, 0] =
tensor([1., 1., 1.])
tensor[..., -1] =
tensor([1., 1., 1.])

modified =
tensor([[0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.]])

joined_0 =
tensor([[0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.]])
joined_1 =
tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1.]])



Tensors can be operated on similar to arrays:
- Indexing/slicing
- Joining/concatenating

## Tensors as Matrices

In [17]:
# Transposition can be done using `.T`
transposed = tensor.T

# Matrix multiplication can be done in the following ways:
matmul1 = tensor @ transposed
matmul2 = tensor.matmul(transposed)
matmul3 = None
torch.matmul(tensor, transposed, out=matmul3)

# Element-wise product can be done in the following ways:
mul1 = tensor * tensor
mul2 = tensor.mul(tensor)
mul3 = None
torch.mul(tensor, tensor, out=mul3)

# Arithmetic operations in-place are denoted by a "_" suffix:
tensor.add_(5)
tensor.t_()

# Converting single-element tensor to Python numerical value
sum = tensor.sum() # Sum of all elements in tensor returns
                   # single-element tensor
item = sum.item() # Convert to Python numerical value
print(item, type(item))

66.0 <class 'float'>


Much like matrices, arithmetic operations can be done on tensors:
- Via operators or functions
- Can happen in-place

## Tensors and References

In [18]:
# Create a PyTorch tensor and get its numpy counterpart
# - `.numpy()` can be used to get the numpy equivalent of a
#   tensor. Notably, both the tensor and the array reference
#   the same memory and changes in one will reflect in the
#   other
torch_tensor = torch.ones(5)
np_array = torch_tensor.numpy()
print(f"torch_tensor =\n{torch_tensor}")
print(f"np_array =\n{np_array}")
print()

# Affect the tensor
torch_tensor.add_(10)
print(f"torch_tensor =\n{torch_tensor}")
print(f"np_array =\n{np_array}")
print()

# Create a numpy array and get its PyTorch counterpart
# - The difference between `torch.from_numpy(np_array)`
#   and `torch.tensor(np_array)` is that, just like in
#   `.numpy()`, the resulting tensor will reference the
#   same memory for `torch.from_numpy(np_array)`
np_array = np.ones(5)
torch_tensor = torch.from_numpy(np_array)
print(f"torch_tensor =\n{torch_tensor}")
print(f"np_array =\n{np_array}")
print()

# Affect the tensor
torch_tensor.add_(10)
print(f"torch_tensor =\n{torch_tensor}")
print(f"np_array =\n{np_array}")
print()

torch_tensor =
tensor([1., 1., 1., 1., 1.])
np_array =
[1. 1. 1. 1. 1.]

torch_tensor =
tensor([11., 11., 11., 11., 11.])
np_array =
[11. 11. 11. 11. 11.]

torch_tensor =
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
np_array =
[1. 1. 1. 1. 1.]

torch_tensor =
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)
np_array =
[11. 11. 11. 11. 11.]



PyTorch tensors and numpy arrays can reference the same memory:
- Typical reference rules apply